function [DelayBias,DelayFrac] = GetAnticipTrials(OM)

%OM, bhv data from Olfac2AFC files generated by OE plugin.

Bad = 1;
Good = 2;

OM = OM(OM(:,7) ~= 0,:);

%OM(OM(:,7) ~= 1,7) = 2;
OM(OM(:,7) == 2 | OM(:,7) == 3 ,7) = 2;
OM(OM(:,7) == 4 | OM(:,7) == 5 | OM(:,7) == 1,7) = 1;

DelayBias = smooth(OM(:,7),30);
DelayBias = DelayBias(2:end-1);

DelayFrac = sum(OM(:,7) == 1) ./ size(OM,1);

figure
plot(DelayBias);
ylim([Bad,Good]);
xlabel('trial');
ylabel('lick');
yticklabels({'Before','','','','','','','','','','After'})
makepretty;