function [TrialBias,AllBias] = GetBiasedLick(OM,Events)

%OM, bhv data from Olfac2AFC files generated by OE plugin.

Right = 2;
Left = 3;

%OM = OM(OM(:,7) ~= 0,:);
OM = OM((OM(:,7) == Right) | (OM(:,7) == Left),:);
TrialBias = smooth(OM(:,7),30);
TrialBias = TrialBias(2:end-1);

figure
plot(TrialBias);
ylim([Right,Left]);
xlabel('trial');
ylabel('choice');
yticklabels({'Right','','','','','','','','','','Left'})
makepretty;


if nargin > 1
    
    Right = 3;
    Left = 4;
    AllBias = smooth(Events(Events == Right | Events == Left),100);
    AllBias = AllBias(2:end-1);

    figure
    plot(AllBias)
    ylim([Right,Left]);
    xlabel('licks');
    ylabel('direction');
    yticklabels({'Right','','','','','','','','','','Left'})
    makepretty;

    
else
    AllBias = [];
end



